version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  database_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: citix-db
    hostname: postgres
    volumes:
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/
      - database_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=via-db
      - POSTGRES_USER=via-user
      - POSTGRES_PASSWORD=via-qwerty
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onelab -d onelab_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    container_name: citix-app
    networks:
      - internal
    ports:
      - "8080:8080"
    volumes:
      - ./config/localconfig.yaml:/root/config/config.yaml
      - .env:/root/.env
    environment:
      - CONFIG_FILE_PATH=config
      - CONFIG_FILE_NAME=config
      - CONFIG_FILE_FORMAT=yaml
    depends_on:
      postgres:
        condition: service_healthy